version: '3.8'

services:
  # Tu aplicaciÃ³n de Python
  app-goles:
    build: .
    image: jenkinsiker:latest
    stdin_open: true # Equivale al -i
    tty: true        # Equivale al -t
    networks:
      - jenkins-net

  # Servidor de Jenkins
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - jenkins-net

networks:
  jenkins-net:

volumes:
  jenkins_data:
